### PR TITLE
Set version for 1.6 release

### PR DESCRIPTION
**Pull request by ryanrichholt**

### CODE REVIEW

**Comment by ryanrichholt** [comment]
@awchrist If you approve this, I'll create and finalize the 1.6 release

**Comment by PedalheadPHX** [comment]
Thanks Ryan, once you and Austin finish the release I'll get @bryce-turner to test it on our end early next week on the dev system Randy setup

**Comment by awchrist** [comment]
@ryanrichholt How do I get a list of the pipelines now? We use to be able to use "jetstream pipelines -L" but now I'm not sure how get the list.

**Comment by awchrist** [comment]
@ryanrichholt I'm having trouble getting the reset directive to work using "reset: predecessors" or "reset: task_name_reset" for the parent task I want to reset when the task resets.

**Comment by PedalheadPHX** [comment]
@ryanrichholt did you have a unit test for this update, or @awchrist can you share the test pipeline you were trying

**Comment by awchrist** [comment]
Here is the main that I am testing out. I make the "sec_job1_job1_job2" fail and then run jetstream pipelines again to get it to restart it. 

```
- name: top_job
  output: file1.txt
  cmd: |
    set -ue

    touch file1.txt


- name: sec_job1
  input: file1.txt
  output: sec_job1.txt
  cmd: |

    set -ue

    touch sec_job1.txt


- name: sec_job2
  input: file1.txt
  output: sec_job2.txt
  cmd: |

    set -ue

    touch sec_job2.txt

- name: sec_job1_job1
  input: sec_job1.txt
  output: sec_job1_job1.txt
  cmd: |

    set -ue

    touch sec_job1_job1.txt

- name: sec_job1_job2
  input: sec_job1.txt
  output: sec_job1_job2.txt
  cmd: |

    set -ue

    touch sec_job1_job2.txt

- name: sec_job2_job1
  input: sec_job2.txt
  output: sec_job2_job1.txt
  cmd: |

    set -ue

    touch sec_job2_job1.txt

- name: sec_job2_job2
  input: sec_job2.txt
  output: sec_job2_job2.txt
  cmd: |

    set -ue

    touch sec_job2_job2.txt

- name: sec_job1_job1_job1
  input: sec_job1_job1.txt
  output: sec_job1_job1_job1.txt
  cmd: |

    set -ue

    touch sec_job1_job1_job1.txt

- name: sec_job1_job1_job2
  after: sec_job1_job1
  output: sec_job1_job1_job2.txt
  reset: predecessors
  cmd: |
    set -ue

    #touch sec_job1_job1_job2.txt

    filename="sec_job1_job1_job2.txt"
    
    if [ ! -f ${filename} ]
    then
      echo "File not found!" 
      touch ${filename}
      exit 1
    else
      echo "File was found!"
      rm ${filename} 
    fi
```

**Comment by ryanrichholt** [comment]
> @ryanrichholt How do I get a list of the pipelines now? We use to be able to use "jetstream pipelines -L" but now I'm not sure how get the list.

```
jetstream pipelines
```

no extra args should list pipelines now

**Comment by ryanrichholt** [comment]
@awchrist 

The relevant code for reset directives is handled by the Workflow class here:
https://github.com/tgen/jetstream/blob/37641c1ea4c3d4c8b15e85b4168cd9095d26f4a9/jetstream/workflows.py#L180-L195

So, if the directive is `predecessors` or `parents`, any tasks one step upstream will be reset. Otherwise the task to reset will be fetched by name. 

I thought I had a test for this, but I also made big changes to how test templates are handled, and accidentlly rm'ed the whole test dir during the process, had to recover from a past commit and redo... in short it was a mess and I dont see the test now. There was a test template that I posted as a suggestion when the issue was raised. We can add the one you posted as well. 

Would the test be run that template twice, it should fail the first time, and pass the second time?

**Comment by awchrist** [comment]
@ryanrichholt Yes, thats how that one should work. The second run should reset the failed task "sec_job1_job1_job2" plus it's predecessor "sec_job1_job1". There are a few more tests I was going to make as well using that template. I could separate out and simplify the different tests I was planning if you think that would be useful?

**Comment by ryanrichholt** [comment]
> @ryanrichholt Yes, thats how that one should work. The second run should reset the failed task "sec_job1_job1_job2" plus it's predecessor "sec_job1_job1". There are a few more tests I was going to make as well using that template. I could separate out and simplify the different tests I was planning if you think that would be useful?

The tests should be as small and simple as possible. Three small tests are much better than one big test. Check out the test/templates/ dir for the templates I've made already

**Pull request merged**
